# Generated by Django 4.2.28 on 2026-08-08 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0009_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labelcategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Label — Category', 'verbose_name_plural': 'Label — Categories'},
        ),
        migrations.AlterModelOptions(
            name='memberlabel',
            options={'ordering': ['category__display_order', 'category__name', 'name'], 'verbose_name': 'Label — Label', 'verbose_name_plural': 'Label — Labels'},
        ),
        migrations.AlterModelOptions(
            name='memberlabelassignment',
            options={'ordering': ['label__name'], 'verbose_name': 'Label — Assignment', 'verbose_name_plural': 'Label — Assignments'},
        ),
        migrations.AlterModelOptions(
            name='memberstatus',
            options={'ordering': ['name'], 'verbose_name': 'Status — Definition', 'verbose_name_plural': 'Status — Definitions'},
        ),
        migrations.AlterModelOptions(
            name='memberstatusassignment',
            options={'verbose_name': 'Status — Assignment', 'verbose_name_plural': 'Status — Assignments'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['priority'], 'verbose_name': 'Rank — Definition', 'verbose_name_plural': 'Rank — Definitions'},
        ),
        migrations.AlterModelOptions(
            name='rankassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Rank — Assignment', 'verbose_name_plural': 'Rank — Assignments'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Rank — Role', 'verbose_name_plural': 'Rank — Roles'},
        ),
        migrations.AlterModelOptions(
            name='roleassignment',
            options={'verbose_name': 'Rank — Role Assignment', 'verbose_name_plural': 'Rank — Role Assignments'},
        ),
        migrations.AddField(
            model_name='hrconfiguration',
            name='home_corp',
            field=models.ForeignKey(blank=True, help_text='Restrict member list and title checks to this corporation. Leave blank to include all members in the configured state.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eveonline.evecorporationinfo'),
        ),
        migrations.CreateModel(
            name='MemberStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('new_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr.memberstatus')),
                ('old_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr.memberstatus')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_status_log_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_status_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status — Log Entry',
                'verbose_name_plural': 'Status — Log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='hr_statuslog_user_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemberLabelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('removed', 'Removed')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr.memberlabel')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_label_log_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_label_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Label — Log Entry',
                'verbose_name_plural': 'Label — Log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='hr_labellog_user_ts_idx')],
            },
        ),
    ]
