# Generated by Django 4.2.28 on 2026-08-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_labelcategory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberStatusLog',
        ),
    ]
