# Generated by Django 4.2.28 on 2026-08-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_role_corp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsnooze',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
