# Generated by Django 4.2.28 on 2026-08-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_memberstatusassignment_status_default_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='title_main_only',
            field=models.BooleanField(default=False, help_text='Only require the main character to hold the in-game title, not all characters.'),
        ),
        migrations.AlterField(
            model_name='role',
            name='corp_title',
            field=models.ForeignKey(blank=True, help_text='EVE title that members holding this role should have on their characters.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_roles', to='corptools.charactertitle'),
        ),
    ]
