# Generated by Django 4.2.28 on 2026-08-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_role_title_main_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('rank_assigned', 'Rank assigned'), ('rank_changed', 'Rank changed'), ('rank_removed', 'Rank removed'), ('status_set', 'Status set'), ('status_cleared', 'Status cleared'), ('label_assigned', 'Label assigned'), ('label_removed', 'Label removed'), ('role_assigned', 'Role assigned'), ('role_removed', 'Role removed'), ('group_sync', 'Group sync')], max_length=20),
        ),
    ]
