# Generated by Django 4.2.28 on 2026-09-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_hrconfiguration_status_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberlabel',
            options={'ordering': ['category__display_order', 'category__name', 'name'], 'verbose_name': 'Label — Definition', 'verbose_name_plural': 'Label — Definitions'},
        ),
        migrations.AlterModelOptions(
            name='rankassignment',
            options={'verbose_name': 'Rank — Assignment', 'verbose_name_plural': 'Rank — Assignments'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role — Definition', 'verbose_name_plural': 'Role — Definitions'},
        ),
        migrations.AlterModelOptions(
            name='roleassignment',
            options={'verbose_name': 'Role — Assignment', 'verbose_name_plural': 'Role — Assignments'},
        ),
    ]
